### PR TITLE
fix(JVariant): try to fix serialization issue for JVariant (fixes #62)

### LINKED ISSUE #62: Wrong serialization of JVariant
JState has a "`List<JVariant>`", which seems incorrect. For example, a block with multiple variants should be 
```
{
  "variants": {
    "": [ {blockModel1}, {blockModel2}, {blockModel3} ]
  }
}
```
which will randomly use one of the variants, instead of:
```
{
  "variants": [
    {"": {blockModel1}},
    {"": {blockModel2}},
    {"": {blockModel3}}
  ]
}
```

### PR DESCRIPTION
**Pull request by chimericdream**
I wasn't able to test locally, but I believe this should fix the incorrect serialization issue with multiple block variants.

Let me know if there are any issues with it! Hopefully it works, though.

### CODE REVIEW

File: src/main/java/net/devtech/arrp/json/blockstate/JVariant.java [hunk 1]
```diff
@@ -13,50 +15,51 @@
 import net.minecraft.util.math.Direction;
 
 public final class JVariant implements Cloneable {
-	private final Map<String, JBlockModel> models = new HashMap<>();
+	private final Map<String, List<JBlockModel>> models = new HashMap<>();
```
Comment (Devan-Kerman) [inline src/main/java/net/devtech/arrp/json/blockstate/JVariant.java:18]: You may need to create a gson serializer like some of the other classes to handle the case where there is only one model. I don't think it's *wrong* per-say but I think it should be done

**Review by Devan-Kerman — CHANGES_REQUESTED** [review]

File: src/main/java/net/devtech/arrp/json/blockstate/JVariant.java (hunk 1 above)
Comment (chimericdream) [reply src/main/java/net/devtech/arrp/json/blockstate/JVariant.java:18]: Done!

**Comment by chimericdream** [comment]
@Devan-Kerman I pushed a small change that should serialize single values as strings like it used to be. Let me know if that works!
